version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: maslim360-postgres
    environment:
      POSTGRES_DB: maslim360
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - maslim360-network

  redis:
    image: redis:7-alpine
    container_name: maslim360-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - maslim360-network

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: maslim360-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/maslim360?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=7d
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../apps/backend:/app
      - /app/node_modules
    networks:
      - maslim360-network
    command: npm run dev

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: maslim360-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../apps/frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - maslim360-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  maslim360-network:
    driver: bridge
